TYPO3:

  Flow:
    security:
      authentication:
        providers:
          'Typo3BackendProvider':
            requestPatterns:
              'Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern': 'backend'
          'Flowpack.Neos.FrontendLogin:Frontend':
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              'Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern': 'frontend'

    aop:
      globalObjects:
        'frontendUserService': 'Flowpack\Neos\FrontendLogin\Domain\Service\UserService'

  Neos:
    typoScript:
      autoInclude:
        'Flowpack.Neos.FrontendLogin': TRUE